name: build ant test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[xunit*]*
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: .packages/*.nupkg
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.28
        with:
          files: **/coverage.opencover.xml
