name: build ant test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build /p:Exclude=[xunit*]*
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: .packages/*.nupkg
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: .testresults/*.xml
          reporter: dotnet-trx